version: "3"
services:
  db:
    image: postgres:latest
    container_name: "chatting-service"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./data:/var/lib/postgresql/data
